replicaCount: 1

image:
  repository: "192.168.1.214:5000/test"
  tag: "v1"
  pullPolicy: IfNotPresent

deployment:
  name: spring-boot-helloworld
  port: 9091

service:
  name: spring-boot-helloworld
  type: NodePort
  port: 9091
  nodePort: 31000
